// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9jg8jV1I-QKy3fYC9KliMpFbCVn-Tthg',
    appId: '1:152326604996:web:0d8b4fe93103ebce5ea191',
    messagingSenderId: '152326604996',
    projectId: 'super-tg-attendance-dashboard',
    authDomain: 'super-tg-attendance-dashboard.firebaseapp.com',
    storageBucket: 'super-tg-attendance-dashboard.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVa1D5Abu3IVx9-cU5jGSkCzqJydM2uog',
    appId: '1:152326604996:android:9f2e883d8c4d0be15ea191',
    messagingSenderId: '152326604996',
    projectId: 'super-tg-attendance-dashboard',
    storageBucket: 'super-tg-attendance-dashboard.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq2UN4UbflDIPUk6KTWO_T-Xngf1GvX9o',
    appId: '1:152326604996:ios:8399cc3c16310f8a5ea191',
    messagingSenderId: '152326604996',
    projectId: 'super-tg-attendance-dashboard',
    storageBucket: 'super-tg-attendance-dashboard.firebasestorage.app',
    iosBundleId: 'com.example.supertg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq2UN4UbflDIPUk6KTWO_T-Xngf1GvX9o',
    appId: '1:152326604996:ios:8399cc3c16310f8a5ea191',
    messagingSenderId: '152326604996',
    projectId: 'super-tg-attendance-dashboard',
    storageBucket: 'super-tg-attendance-dashboard.firebasestorage.app',
    iosBundleId: 'com.example.supertg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9jg8jV1I-QKy3fYC9KliMpFbCVn-Tthg',
    appId: '1:152326604996:web:8b2e0b1aa504838e5ea191',
    messagingSenderId: '152326604996',
    projectId: 'super-tg-attendance-dashboard',
    authDomain: 'super-tg-attendance-dashboard.firebaseapp.com',
    storageBucket: 'super-tg-attendance-dashboard.firebasestorage.app',
  );
}
